security:
  basic:
    enabled: false

management:
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.hs-service-registry.credentials.uri:http://127.0.0.1:8761}/eureka/

#greeting: Hello %s from GitHub!
spring:
  profiles: dev
greeting: Howdy %s! from dev

spring:
  profiles: stage
greeting: Howdy %s! from stage

spring:
  profiles: prod
greeting: Howdy %s! from prod


